### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtsass#1]
Hi @yann-lty thanks for this project. Now, this project seems unmaintained.

I am core developer for [spyder-ide](https://github.com/spyder-ide/spyder) and we are planning to use QSS  with SASS for version 4.0 (under development) I would really like to update the current library and maintain it.

Would you be ok with this? in which case could we transfer ownership to spyder-ide organization?

**Comment by yann-lty** [comment]
Hi @goanpeca ! 
Thanks for your message and sure, I'll be glad to see this project maintained. 
Do I have to be part of the spyder-ide organization to transfer the ownership (never done that before) ?

**Comment by goanpeca** [comment]
@yann-lty I don't think so, I can add you as maintainer once you are there is case you want to add to it :-)

**Comment by yann-lty** [comment]
I tried to transfer ownership, but get this error:

> You don’t have the permission to create repositories on spyder-ide

Also, the doc says:

> Transfer this repository to another user or to an organization where **you have the ability to create repositories**.

**Comment by goanpeca** [comment]
Ahhh, sorry, in that case can you transfer to me, and then I can transfer to spyder-ide ? then I can add back permissions to you.

Thanks

**Comment by yann-lty** [comment]
Sure that sounds great !
Just transferred you the ownership :)

**Comment by goanpeca** [comment]
@yann-lty done, thanks :-). I will update the code a bit to include other gradients and add a few tests ;-)

**Comment by yann-lty** [comment]
Great ! 
I haven't launched this code in a while, but let me know if you have any question.
I guess we can close this issue then :)
