### ISSUE TITLE
Create PyPI package

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtsass#17]

**Comment by danbradham** [comment]
Yeah absolutely.

**Comment by KurtJacobson** [comment]
Is there any update / estimated release date for a qtsass PyPI package? Thanks.

**Comment by andvgal** [comment]
PIP does support install from Git, but making a PyPI release does not really take time and you can automate that with CID (https://github.com/futoin/cid-tool) leading to just:

1. `cid tag master` - to update for release & tag
2. `cid ci_build vX.Y.Z pypi` - to clean checkout, build, test and upload
