### ISSUE TITLE
CLI - build/watch directory

### ISSUE THREAD

**Issue by danbradham** [spyder-ide/qtsass#18]
The current CLI only supports building and watching a single sass file. This may be suitable for small projects, but, large projects tend to have more varied structures. For example, a project may have a base stylesheet with dark and light variants.

- /scss
  - _base.scss
  - dark.scss
  - light.scss

To support the above scenario we should add a CLI option -d/--directory that will compile and watch for changes in all the scss files contained in the directory except for those starting with an underscore. The -d/--directory and the -f/--file options should be mutually exclusive raising an error when both are provided. When using the -d flag the -o flag specifies an output directory for the compiled css.

Valid usages
```
qtsass -d scss -o css
qtsass -d scss -o css -w
qtsass -f scss/dark.scss -o css/dark.css
qtsass -f scss/dark.scss -o css/dark.css -w
```

**Comment by goanpeca** [comment]
@danbradham how about having a `-p` `--path` option and just point to either a specific file, or a folder

```
qtsass -p scss/ -o css
qtsass -p scss/ -o css -w
qtsass -p scss/dark.scss -o css/dark.css
qtsass -p scss/dark.scss -o css/dark.css -w
```

**Comment by danbradham** [comment]
Yeah, that's good. We can make sure the CLI help string makes all these use cases apparent. Python libsass also ships with a setuptools build command that is pretty nifty, let's you specify all your scss files liiiike:
```
setup(
...
    sass_manifests={
       'package': ('/scss', '/css')
    },
)
```
Kind of nifty, maybe we can support that down the line.
