### ISSUE TITLE
Align api behavior with libsass?

### ISSUE THREAD

**Issue by danbradham** [spyder-ide/qtsass#24]
Looking over the python libsass api, I realized that the qtsass api is not aligned. Libsass has a single compile method that performs different operations based on which mode argument is provided.

`compile(string='#sass string', **kwargs)` - compiles a source string
`compile(filename='file.scss', **kwargs)` - compiles a source file, delegates to compile_filename()
`compile(dirname='./dir', **kwargs)` - recursively compiles source files, delegates to compile_dirname()

PR #23 renames `compile_and_save` to `compile_filename`, and adds the `compile_dirname` api method. So qtsass will now have api names that align with libsass. The question is, how closely should we align the qtsass api behavior with libsass? I can imagine two options:

1. Match behavior fully 
    - `compile` is the only public api method
    - `compile` delegates to `compile_filename` and `compile_dirname` based on arguments
2. Be more explicit 
    - `compile` should ONLY compile a source string
    - `compile`, `compile_filename`, and `compile_dirname` are all public methods

I think I prefer option **2**.

In addition to the above, our api should allow users to pass the full breadth of keyword arguments to the underlying libsass.compile calls. [Here's the documentation for libsass.compile.](https://sass.github.io/libsass-python/sass.html#sass.compile)

What do you think? @goanpeca

**Comment by goanpeca** [comment]
hello :-)

I agree with option 2. We can be pythonic and explicit without having to replicate a single universl method tht does everything.

**Comment by goanpeca** [comment]
So we should close this one (closed by #23?) @danbradham ?

**Comment by danbradham** [comment]
Actually the api needs a slight adjustment to match option 2, so we can leave it open for now.

**Comment by goanpeca** [comment]
ahh ok

**Comment by danbradham** [comment]
closed by #27
