### ISSUE TITLE
Move primary maintainer back to spyder contributors?

### ISSUE THREAD

**Issue by danbradham** [spyder-ide/qtsass#33]
At this point I should probably bow out as primary maintainer of this project. I never had time to make a release and probably won't have much time going forward to address issues that may arise.

@goanpeca or someone else who is more familiar with spyder projects generally would make a better primary maintainer. What do you think @goanpeca?

I never felt comfortable making a release as someone peripheral to the spyder organization.

**Comment by goanpeca** [comment]
Sure thing @danbradham :-). We will appreciate your input on issues still, even if you think it will be difficult to find time to fix things as they pop.
