### ISSUE TITLE
qlineargradient x1,y1,x2,y2 values can be floats!

### ISSUE THREAD

**Issue by ewerybody** [spyder-ide/qtsass#42]
Turns out its actually not a problem to put float values into the `x1,y1,x2,y2` coordinate values of a qlineargradient liek:

    s = 'background: qlineargradient(x2: 0.0, y2:2.0, stop:0 rgb(80,20,20), stop:1 rgb(75,175,75));'
    x.btn.setStyleSheet(s)

Unfortunately when compiling with **qtsass** the [regular expression in conformers.py line 49](https://github.com/spyder-ide/qtsass/blob/master/qtsass/conformers.py#L49) breaks on these. As soon as one replaces the floats with ints all is fine again.

Unfortunately again I have no clue how to make the **re** accept float values instead of the ints or anything else. It works with variables for instance.

    qss_pattern = re.compile(
        r'qlineargradient\('
        r'((?:(?:\s+)?(?:x1|y1|x2|y2):(?:\s+)?[0-9A-Za-z$_-]+,?)+)'  # coords 🤷‍♂️🤷‍♂️🤷‍♂️
        r'((?:(?:\s+)?stop:.*,?)+(?:\s+)?)?'  # stops
        r'\)',
        re.MULTILINE,
    )
This is probably an easy one for someone who's into regular expressions?

**Comment by goanpeca** [comment]
@ewerybody sure, I will fix it ;-),

Thanks for the help with the project!

**Comment by ewerybody** [comment]
Oh a co-worker was just helping me with the re 🙈
I almost had it myself. Sure one needs to escape the dot...

qss_pattern = re.compile(
    r'qlineargradient\('
    r'((?:(?:\s+)?(?:x1|y1|x2|y2):(?:\s+)?[0-9A-Za-z$_\.-]+,?)+)'  # coords
    r'((?:(?:\s+)?stop:.*,?)+(?:\s+)?)?'  # stops
    r'\)',
    re.MULTILINE,
)

Voilà! I'll put up a PR?

**Comment by ewerybody** [comment]
Ooh I need the other one to finish first? Sorry. No rush!! 🙈
