### ISSUE TITLE
rgba function breaks on incoming 8bit ints

### ISSUE THREAD

**Issue by ewerybody** [spyder-ide/qtsass#43]
If you write QSS right away you might also want 0 to 255 values as alpha which is not CSS conform!

So the [rgba function](https://github.com/spyder-ide/qtsass/blob/master/qtsass/functions.py#L20) will turn `128` to `12800%`.

... oh while writing this I fixed it already. Had problems with the debugger first. But this is solved now as well 🌈.
By that way I separated the rgba test functions...

This might also be in the PR, right?

**Comment by goanpeca** [comment]
>This might also be in the PR, right?

Sure!
