### ISSUE TITLE
install latest version

### ISSUE THREAD

**Issue by rolivav** [spyder-ide/qtsass#45]
Hello, I am trying to install the latest version of qtsass.
When I do `pip install qtsass` it seems I am getting a very old version. What do I do to install the version you have tested in master?

**Comment by vitlav** [comment]
Yes, please make a new release.

**Comment by goanpeca** [comment]
@rolivav @vitlav will make a release in the following week!

Thanks for the interest in the project

**Comment by nonamedotc** [comment]
I am packaging this for Fedora. Any ETA on release of version 0.3? Thanks.

**Comment by goanpeca** [comment]
Qtsass 0.3.0 is now available https://pypi.org/project/qtsass/
