### ISSUE TITLE
Improve logging configuration

### ISSUE THREAD

**Issue by danbradham** [spyder-ide/qtsass#46]
Currently qtsass is using basicConfig to configure the root logger. This is generally okay when qtsass is used only from the CLI. When used as a library this is problematic, and can propagate to other library's loggers. We should use logging best practices for a library:

```
# Add a null handler
import logging
logging.getLogger('qtsass').addHandler(logging.NullHandler())
```

We can add an enable_logging function to the api that accepts an optional logging level.

```
def enable_logging(level=None):
    if level is None:
        level = os.environ.get('QTSASS_DEBUG', logging.WARNING)
    logger = logging.getLogger('qtsass')
    logger.setLevel(level)
```

A --debug flag can be added to the cli to allow users to enable debug logging on the cli.

With that users would have the following options to configure logging:

1. Set the QTSASS_DEBUG environment variable
2. Use the --debug cli flag
3. Call qtsass.enable_logging(logging.DEBUG)
3. Add custom logging handlers to the qtsass logger

**Comment by goanpeca** [comment]
Sounds good @danbradham, want to work on it :-) ?

**Comment by danbradham** [comment]
You bet :).
