### ISSUE TITLE
Update 'collections' imports for Python 3.3+

### ISSUE THREAD

**Issue by dpizetta** [spyder-ide/qtsass#52]
Hi, from our tests in qdarkstyle, some warnings have been raised asking to change the imports of collections to the new package hierarchy, Python >= 3.3.

```
lib\site-packages\qtsass\api.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Sequence, Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

At line: https://github.com/spyder-ide/qtsass/blob/91c546f5b484eb4a697ea52496311bf3f38f62bd/qtsass/api.py#L16

More info: https://docs.python.org/3.4/library/collections.abc.html

If wanted, I can submit a PR :) Tks

**Comment by goanpeca** [comment]
Will make a fix and a release ;-)
