### ISSUE TITLE
Unsupported qradialgradient

### ISSUE THREAD

**Issue by laurapons** [spyder-ide/qtsass#57]
qradialgradient is not supported. Example of typical usage:

```
QRadioButton::indicator:checked
{
	background-color: qradialgradient(
		cx: 0.5, cy: 0.5,
		fx: 0.5, fy: 0.5,
		radius: 1.0,
		stop: 0.25 #78879b,
		stop: 0.3 #302F2F
	);
}
```

**Comment by ccordoba12** [comment]
Hey @laurapons. thanks for reporting. You're welcome to add support for `qradialgradient` if you need it for your projects. Unfortunately, we don't have right now the bandwidth to handle that.

**Comment by regrainb** [comment]
Can you consider that patch to handle the radial gradient?
[qradialgradient.diff.txt](https://github.com/spyder-ide/qtsass/files/7640356/qradialgradient.diff.txt)

At least for @laurapons , you can directly apply that patch on the QtSass sources available in your <python>/Lib\site-packages\qtsass folder.

**Comment by ccordoba12** [comment]
@regrainb, thanks for chiming in! Please create a pull request for your patch (it should be really straightforward), then we could include it in our next release.

It's not that we don't want to do it, it's simply that we have too many other things to do. Thanks for understanding.

**Comment by regrainb** [comment]
@ccordoba12: I don't have write access on qtsass, so I can't create a branch to pull it.
Can you take me write access? or explain me how to create the pull request without it?

**Comment by ccordoba12** [comment]
You can fork this repo, create a branch for your work and submit your pull request from it. We don't work with in-repo branches in our organization, so that's what we all do, actually.

**Comment by regrainb** [comment]
Pull request created: https://github.com/spyder-ide/qtsass/pull/59

**Comment by regrainb** [comment]
@ccordoba12 : I created the pull request. Must I do something else to have it integrated on your side?
I need it for my company, to simplify the deployment of this feature.
