### ISSUE TITLE
Create conda-forge package

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtsass#6]

**Comment by goanpeca** [comment]
https://github.com/conda-forge/staged-recipes/pull/8201

**Comment by goanpeca** [comment]
@danbradham and @ccordoba12 is it ok to add you as maintainers over https://github.com/conda-forge/staged-recipes/pull/8201 ?

**Comment by ccordoba12** [comment]
Yep, I'm ok with it.
