### ISSUE TITLE
Drop support for Python 2.7, 3.5, and 3.6

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtsass#67]
Seems like `libssas-python` dropped support for Python 2.7 https://github.com/sass/libsass-python/commit/d333e3c419f48f4b2d96528cb4c83db1f02adaec (there is no release with that change for the moment but still I guess the latest release that supports Python 2.7 will be the current one `0.21.0`).

Taking the opportunity, maybe removing support for others already out of date Python versions like 3.5 and 3.6 could be worty.

Also, should we release QtSASS v0.3.2 adding a constraint to `libsass<=0.21.0` before proceeding with dropping the support for Python <=3.6 @ccordoba12 ?

**Comment by ccordoba12** [comment]
> Also, should we release QtSASS v0.3.2 adding a constraint to libsass<=0.21.0 before proceeding with dropping the support for Python <=3.6 @ccordoba12 ?

Yeah, I think that's a good idea. Then you can remove that constrain in version 0.4.0

**Comment by dalthviz** [comment]
Note: `libsass-python` v0.22.0 was released - https://github.com/sass/libsass-python/releases/tag/0.22.0
